version: '3'
services:
  app:
    container_name: goginCasbin
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - template-postgres
    networks:
      - template


  template-postgres:
    image: postgres:latest
    container_name: golang_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - template

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  startup_template:
    driver: bridge